AWSTemplateFormatVersion: '2010-09-09'
Description: 'Temporary IAM user for setting up GitHub OIDC provider'

Resources:
  LatticeSetupUser:
    Type: AWS::IAM::User
    Properties:
      UserName: lattice-setup-user
      Tags:
        - Key: Purpose
          Value: GitHubOIDCSetup
        - Key: Temporary
          Value: 'true'

  LatticeSetupPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: LatticeSetupPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # OIDC Provider permissions
          - Effect: Allow
            Action:
              - iam:CreateOpenIDConnectProvider
              - iam:GetOpenIDConnectProvider
              - iam:ListOpenIDConnectProviders
              - iam:TagOpenIDConnectProvider
            Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
          
          # IAM Role permissions
          - Effect: Allow
            Action:
              - iam:CreateRole
              - iam:GetRole
              - iam:UpdateAssumeRolePolicy
              - iam:TagRole
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              - iam:ListAttachedRolePolicies
            Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/LatticeGitHubActions-*'
          
          # IAM Policy permissions
          - Effect: Allow
            Action:
              - iam:CreatePolicy
              - iam:GetPolicy
              - iam:CreatePolicyVersion
              - iam:GetPolicyVersion
              - iam:ListPolicyVersions
              - iam:SetDefaultPolicyVersion
            Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/LatticeGitHubActions-*'
          
          # Read-only permissions for validation
          - Effect: Allow
            Action:
              - iam:GetUser
              - iam:ListUsers
              - sts:GetCallerIdentity
            Resource: '*'
          
          # Managed policy access (read-only to attach PowerUserAccess)
          - Effect: Allow
            Action:
              - iam:GetPolicy
              - iam:ListPolicies
            Resource: 'arn:aws:iam::aws:policy/PowerUserAccess'

      Users:
        - !Ref LatticeSetupUser

  LatticeSetupAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref LatticeSetupUser

Outputs:
  AccessKeyId:
    Description: 'Access Key ID for the setup user'
    Value: !Ref LatticeSetupAccessKey
    Export:
      Name: LatticeSetupAccessKeyId

  SecretAccessKey:
    Description: 'Secret Access Key for the setup user'
    Value: !GetAtt LatticeSetupAccessKey.SecretAccessKey
    Export:
      Name: LatticeSetupSecretAccessKey

  UserArn:
    Description: 'ARN of the setup user'
    Value: !GetAtt LatticeSetupUser.Arn
    Export:
      Name: LatticeSetupUserArn